social:
  - identifier: github
    name: GitHub
    url: 'https://github.com/CaiJimmy/hugo-theme-stack'
    params:
      icon: brand-github
  - identifier: twitter
    name: Twitter
    url: 'https://twitter.com'
    params:
      icon: brand-twitter
  - identifier: instagram
    name: Instagram
    url: 'https://instagram.com'
    params:
      icon: instagram
  - identifier: linkedin
    name: Linkedin
    url: 'https://linkedin.com'
    params:
      icon: linkedin
