social:
  - identifier: github
    name: GitHub
    url: 'https://github.com/MuhammadTatma'
    params:
      icon: brand-github
  - identifier: Mail
    name: Mail
    url: 'mailto:muh.tatma442@gmail.com'
    params:
      icon: mail
  - identifier: instagram
    name: Instagram
    url: 'https://www.instagram.com/tatmainnulq/'
    params:
      icon: instagram
  - identifier: linkedin
    name: Linkedin
    url: 'https://www.linkedin.com/in/muhammad-tatma/'
    params:
      icon: linkedin
